name: dtm_front
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.24.0
  json_serializable: ^3.5.1

dev_dependencies: 
  build_runner: ^1.11.1

flutter:

  uses-material-design: true

